#! /usr/bin/php -q
<?php
require_once ("Botwiki.php");
/*  =======================================================
                 Colores texto
    =========================================================*/
$colorVerde = "\033[1;32m";
$colorRojo = "\033[1;31m";
$colorBlancoB = "\033[1;37m";
$colorTurquesa = "\033[1;36m";
$colorRosa = "\033[1;35m";
$colorMagenta = "\033[0;35m";
$colorAmarillo = "\033[1;33m";
$finColor = "\033[0m";

/*  =======================================================
                 Atributos
    =========================================================*/
	
	/*== Valores login bot == */
$usuario = "<USUARIO>"; // Nombre del bot
$contrasenna = "<CONTRASEÑA>"; // Contraseña que usa el bot para iniciar sesión en es:Wikipedia
$comentario = "Bot: Retirando coordenadas trasladadas a Wikidata";

    /* == Programa == */
$plantilla = "Ficha de localidad"; //Plantilla que va a buscar en la páginas de es:wikipedia para modificar
$categoria = "Wikipedia:Artículos con coordenadas locales";
//$archivo = ;
$pagina = "Usuario:Miguillen/Población";
//$busqueda = "categoría"
$busqueda = "inclusión";
//$busqueda = "página";

   /* == Valores iniciales de las variables del programa == */ 
$todos = false; // Variable que establece si hace cambios en todas las páginas
$siguiente = true; 
$contadorLista = 1;
$contadorNo = 0;
$contadorSi = 0;
$contadorError = 0;
$cont = "";
/*  =======================================================
                 Programa
    =========================================================*/
	
   /*== Crear objeto Botwiki == */
$botwiki = new Botwiki;

   /*== login bot == */
$botwiki->login($usuario, $contrasenna);

do {
    switch ($busqueda) {
        case "página":
            $lista = array($pagina,"cont" => "");
	    break;
	    case "inclusión":
            $lista = $botwiki->listPlantilla($plantilla,$cont);
	    break;
	    case "categoría":
	        $lista = $botwiki->listCat($categoria,$cont);
	    break;
	}
    //print_r($lista);
	$contenidoLista = count($lista)-1;
    echo " ".$colorBlancoB.$contadorLista.") Cargados ". $contenidoLista. " páginas que contienen la [[Plantilla:".$plantilla."]]".$finColor."\r\n";
	$cont = $lista['cont'];
	$contadorLista++;
    unset($lista['cont']);	//Quitamos el elemento con el código de continuar para que no entorpezca    

	for($k = 0; $k < count($lista); $k++){
	    $stringPagina = false;
	    while (!$stringPagina){
		    $paginaEncontrada = $botwiki->getArticulo($lista[$k]);
		    $stringPagina = $paginaEncontrada["query"]["pages"][key($paginaEncontrada["query"]["pages"])]["revisions"][0]["*"];
		}
		$stringFicha1 = $botwiki->CapturarPlantilla($lista[$k], $plantilla);
		$stringFicha = $stringFicha1[0];
		$stringCoord = $botwiki->CapturarPlantilla($lista[$k],"Coord");
		$arrayFicha1 = $botwiki->getPlantillaInArray($lista[$k],$plantilla,true);
		$arrayFicha = $arrayFicha1[0];
		$arrayCoord = $botwiki->getPlantillaInArray($lista[$k],"Coord",false);
		$tituloPagina = $paginaEncontrada["query"]["pages"][key($paginaEncontrada["query"]["pages"])]["title"];
		$indice=0;
		$esp = 0;
        if ((!$stringFicha) || (!$arrayFicha)) {
		    echo $colorRojo." No obtenido datos en página: [[".$tituloPagina."]]\r\n".$finColor;
		    $contadorError++;
		    continue;
		}
		/* == Parámetros que eliminamos de la plantilla == */
		unset($arrayFicha['coor']);
		unset($arrayFicha['coord']);
		unset($arrayFicha['coordenadas']);
		unset($arrayFicha['lat']);
		unset($arrayFicha['long']);
		unset($arrayFicha['lon']);
		unset($arrayFicha['latd']);
		unset($arrayFicha['latm']);
		unset($arrayFicha['lats']);
		unset($arrayFicha['latNS']);
		unset($arrayFicha['longd']);
		unset($arrayFicha['longm']);
		unset($arrayFicha['longs']);
		unset($arrayFicha['longEW']);
		unset($arrayFicha['lond']);
		unset($arrayFicha['lonm']);
		unset($arrayFicha['lons']);
		unset($arrayFicha['lonEW']);
		/*===================================================*/
		
		/*== Reconstruimos la plantilla a partir del array == */
		
		/* 1) Averiguamos cual va a ser el nombre de parámetro más largo, ahora la clave del array para alinear (=)*/
		foreach ($arrayFicha as $clave => $valor) {
			if (strlen($clave) > $esp){
			   $esp = strlen($clave);
			}
		}
		/* 2) Creamos cada línea de | parámetro = valor */
		foreach ($arrayFicha as $clave => $valor) { 
			$long = $esp - strlen(utf8_decode($clave));
			$linea[$indice] = "| ".$clave.str_repeat(" ",$long)." = " .$valor;
			$indice++;
		}
		/* 3) Montamos plantillas */
		$parametros = implode("\r\n", $linea); // Ponemos cada parámetro en una línea
		$resultadoFicha = "{{".$plantilla."\r\n".$parametros."\r\n}}"; // Ponemos los parámetros dentro de la plantilla
		$resultadoPagina = str_replace($stringFicha,$resultadoFicha,$stringPagina);
		
        /*== Quitamos si encuetra una plantilla coord con display = title == */
		//print_r($arrayCoord);
        for ($ki = 0; $ki < count($arrayCoord); $ki++) {
		    if (!array_key_exists("display",$arrayCoord[$ki])){
			    continue;
			}
			if ($arrayCoord[$ki]["display"] == "title"){
                echo "encontrado".$stringCoord[$ki]."\r\n";
                				
				$resultadoPagina = str_replace($stringCoord[$ki],"",$resultadoPagina);
			} elseif ($arrayCoord[$ki]["display"] == "inline,title"){
				$arrayCoord[$ki]["display"] = "inline";
				$indice = 0;
				unset($parametros);
				unset($linea);
				foreach ($arrayCoord[$ki] as $clave => $valor) { 
					if (is_numeric($clave)){
						$linea[$indice] = "|".$valor;
					} else {
					   $linea[$indice] = "|".$clave."=" .$valor;
					}
					$indice++;
				}
				$parametros = implode($linea); // Ponemos todos los parámetros en una línea
				$resultadoCoord = "{{Coord".$parametros."}}"; // Ponemos los parámetro dentro de la plantilla
				$resultadoPagina = str_replace($stringCoord[$ki],$resultadoCoord,$resultadoPagina);	
			}
		}
		
		$dif = $botwiki->getCambio($resultadoPagina, $lista[$k]);
		
		if ($dif != ""){
		    //system("clear"); //Limpiamos pantalla
			echo "\r\n" .$colorRosa.">>>".$colorBlancoB." ".$tituloPagina." ".$colorRosa."<<<".$finColor."\r\n\r\n";
			echo $dif."\r\n";
            

			do {
				if (!$todos) {
					echo "\r\n".$colorBlancoB." ¿Desea realizar los cambios? ".$finColor."(".$colorTurquesa."[S]".$finColor."í, ".$colorTurquesa."[N]".$finColor."o, ".$colorTurquesa."[T]".$finColor."odos, ".$colorTurquesa."[C]".$finColor."errar): ";
					$confirmacion = trim(fgets(STDIN));
					$teclaNo = false;
				}
				if (($confirmacion == "s") || ($confirmacion == "t") || ($todos) ){
					echo $colorBlancoB." Realizando cambios en [[".$tituloPagina."]]".$finColor."\r\n";
					$hecho = $botwiki->setArticulo($lista[$k],$resultadoPagina,$comentario);
					if ($confirmacion == "t"){
					    $todos = true;
					}
				} else if ($confirmacion == "n") { 
					echo $colorBlancoB." Cancelados cambios en [[".$tituloPagina."]]".$finColor."\r\n";
					$hecho = false;
					continue;
				} else if ($confirmacion == "c"){
				    echo $colorBlancoB." Cancelados cambios en [[".$tituloPagina."]]".$finColor."\r\n";
					echo $colorBlancoB." Cerrando programa".$finColor."\r\n";
					return;
				} else {
					$teclaNo = true;
				}	
			} while($teclaNo);
			
            if ($hecho)	{
			    $contadorSi++;
            } else {
			    $contadorError++;
            }			
		} else {
			echo $colorAmarillo." No hay cambios necesarios en [[".$lista[$k].$finColor."]]\r\n";
            $contadorNo++;			
		}
		unset($arrayFicha);
		unset($linea);
		unset($arrayCoord);
	}
	
	$totalEdiciones = $contadorSi + $contadorNo + $contadorError;
	echo $colorBlancoB." Estadítica: ".$finColor."Cambios: ".$colorVerde.$contadorSi.$finColor." - Omitidos: ".$colorAmarillo.$contadorNo.$finColor." - Erróres: ".$colorRojo.$contadorError.$finColor." - Total:  ".$colorBlancoB.$totalEdiciones.$finColor."\r\n";
} while ($cont);
echo " ".$colorBlancoB."Terminado programa\r\n".$finColor."\r\n";
